global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["jenkins-host:8080"]  # <<-- CAMBIA a tu host/puerto reales de Jenkins

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
